# https://docs.fluentbit.io/manual/pipeline/inputs/forward
# 这个用于fluent-bit和fluentd之间转发消息
# 像一些支持fluent协议的的应用也可以使用:
#   * dockerlog, 配置log driver将日志以fluent协议转发到fluent-bit

[INPUT]
    Name              forward
    Listen            0.0.0.0
    Port              24224
    Buffer_Chunk_Size 1M
    Buffer_Max_Size   6M